### ISSUE TITLE
Number of Message Visible 1HR Rollups are Inaccurate

### ISSUE THREAD

**Issue by TheConnMan** [netuitive-community-packages/netuitive-packages-aws-sqs#14]
The metric `aws.sqs.approximatenumberofmessagesvisible` is a sum, so the hourly rollups are summed 5 min rollups. This is incorrect. Other metrics listed as `sum` may also need reevaluation.

**Comment by codytipton** [comment]
`"match": "aws\\.sqs\\.approximatenumber.*",`

Below are the metrics which will match the rule.  I don't believe any of these should be sums based on their descriptions.  My thinking is they should be avg.  

**ApproximateNumberOfMessages** - Returns the approximate number of messages available for retrieval from the queue.

**ApproximateNumberOfMessagesDelayed** - Returns the approximate number of messages in the queue that are delayed and not available for reading immediately. This can happen when the queue is configured as a delay queue or when a message has been sent with a delay parameter.

**ApproximateNumberOfMessagesNotVisible** - Returns the approximate number of messages that are in flight. Messages are considered to be in flight if they have been sent to a client but have not yet been deleted or have not yet reached the end of their visibility window.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.h

**Comment by TheConnMan** [comment]
Yes, all of those should be averages. Thanks for taking a look at this so quickly.
